sudo: false
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - ./dev-bin/travis-prepare.sh
script:
  PERL5OPT=-MDevel::Cover prove -lv t && cover -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
